### ISSUE TITLE
Latitude issue

### ISSUE THREAD

**Issue by kksaney** [tejakattenborn/dji_h20t_rpeg_to_tif#1]
After converting, the - latitude (west hemisphere) turned to + latitude (east hemisphere).
Ex) 30.00 -120.00 -> 30.00 120.00

I manually changed it before running my files in the Pix4D, but it would be great if we can edit it.

**Comment by jasonrmh** [comment]
I have noticed this also, negative values are converted to positive and so the location is changed.

**Comment by Thor-ge** [comment]
Hey everyone, I ran into the same problem. I'm working on the southern hemisphere, after converting the images their location is mirrored north of the equator. Tried multiplying the latitude in the script by -1, which unfortunately didn't change the result. Does anyone know a way to change from latitude north to latitude south in the exif? Dealing with picture counts in the high hundreds...

**Comment by tejakattenborn** [comment]
Sorry for getting back to this so late. The recent updates should fix this issue. Please, let me know if problems persist.
