### ISSUE TITLE
Data error

### ISSUE THREAD

**Issue by DSFID** [tejakattenborn/dji_h20t_rpeg_to_tif#3]
hi Teja, thanks for your great job.

I just new to work with coding.
I use your script, everything works fine.
but the results are still not satisfactory, the results of the Tiff file is all white.
once I process on metashape, still not getting the temperature difference as it should

attached the Tiff that I have based on your sample data, is it correct?
[DJI_20220602143532_0191_T.zip](https://github.com/tejakattenborn/dji_h20t_rpeg_to_tif/files/10637368/DJI_20220602143532_0191_T.zip)

**Comment by tejakattenborn** [comment]
Please view the tif-file in a GIS environment or R/Python. The standard viewers in Ubuntu/Windows/etc... are not designed to resolve float rasters.
